USE Entry_MC;

SELECT * FROM VEHICULOS V
INNER JOIN TIPOS_VEHICULO TV ON V.TIPO_VEHICULO = TV.ID_TIPO_VEHICULO;

SELECT NOMBRE_USUARIO, NUMERO_DOCUMENTO, NOMBRE_DOCUMENTO FROM USUARIOS U
INNER JOIN TIPO_DOCUMENTOS TD ON U.TIPO_DOCUMENTO = TD.ID_TIPO_DOCUMENTO;

SELECT * FROM ROLES R
INNER JOIN PERMISOS P ON R.ID_ROL = P.ROL_PERMISO;

SELECT * FROM REGISTRO_ENTRADA RE
RIGHT JOIN VEHICULOS V ON RE.ID_VEHICULO = V.ID_VEHICULO;

SELECT U.NOMBRE_USUARIO, R.NOMBRE_ROL, R.ID_ROL, DESCRIPCION_ROL FROM USUARIOS U
INNER JOIN ROLES R ON U.NOMBRE_ROL = R.ID_ROL;

SELECT * FROM USUARIOS WHERE NOMBRE_ROL = 1;
SELECT * FROM USUARIOS WHERE TIPO_DOCUMENTO = 2;
SELECT COUNT(*) FROM USUARIOS;

SELECT * FROM orden_trabajo OT
LEFT JOIN VEHICULOS V ON OT.Id_Vehiculo = V.Id_Vehiculo;






